name = "drive"
type = "webpack"
workers_dev = true
account_id = "c634e394a2d1f4db901d785ed2c214b4"
zone_id = "b4ac4b078492d729cae47aefc54a0a5c"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "9f29fb3947df4b1ca3570f38772d29ce", id = "09b0cf433f394b309d35d1ff3bd0bf39" }
]

[env.staging]
name = "drive-staging"
